import type { ClipboardEvent } from './ClipboardEvent';
import type { DeviceEvent } from './DeviceEvent';
import type { DisplayEvent } from './DisplayEvent';
import type { DropEvent } from './DropEvent';
import type { Event } from './Event';
import type { GamepadAxisEvent } from './GamepadAxisEvent';
import type { GamepadBatteryEvent } from './GamepadBatteryEvent';
import type { GamepadButtonEvent } from './GamepadButtonEvent';
import type { GamepadSensorEvent } from './GamepadSensorEvent';
import type { KeyEvent } from './KeyEvent';
import type { LocaleEvent } from './LocaleEvent';
import type { PointerEvent } from './PointerEvent';
import type { QuitEvent } from './QuitEvent';
import type { TextEvent } from './TextEvent';
import type { ThemeEvent } from './ThemeEvent';

export * from './ClipboardEvent';
export * from './DeviceEvent';
export * from './DisplayEvent';
export * from './DropEvent';
export * from './Event';
export * from './GamepadAxisEvent';
export * from './GamepadBatteryEvent';
export * from './GamepadButtonEvent';
export * from './GamepadSensorEvent';
export * from './KeyEvent';
export * from './LocaleEvent';
export * from './PointerEvent';
export * from './QuitEvent';
export * from './TextEvent';
export * from './ThemeEvent';
export * from './WindowEvent';

export type InputsEventMap = {
  quit: [event: QuitEvent];
  terminating: [event: Event];
  'low-memory': [event: Event];
  locale: [event: LocaleEvent];
  theme: [event: ThemeEvent];
  orientation: [event: DisplayEvent];
  'display-added': [event: DisplayEvent];
  'display-removed': [event: DisplayEvent];
  'display-move': [event: DisplayEvent];
  'display-change': [event: DisplayEvent];
  'key-down': [event: KeyEvent];
  'key-up': [event: KeyEvent];
  'keymap-change': [event: Event];
  text: [event: TextEvent];
  'text-edit': [event: TextEvent];
  'text-edit-candidates': [event: TextEvent];
  'device-added': [event: DeviceEvent];
  'device-removed': [event: DeviceEvent];
  'device-updated': [event: DeviceEvent];
  'device-approved': [event: DeviceEvent];
  'device-denied': [event: DeviceEvent];
  'pointer-move': [event: PointerEvent];
  'pointer-down': [event: PointerEvent];
  'pointer-up': [event: PointerEvent];
  'pointer-wheel': [event: PointerEvent];
  'pointer-cancel': [event: PointerEvent];
  'pointer-in': [event: PointerEvent];
  'pointer-out': [event: PointerEvent];
  'gamepad-battery': [event: GamepadBatteryEvent];
  'gamepad-axis': [event: GamepadAxisEvent];
  'gamepad-down': [event: GamepadButtonEvent];
  'gamepad-up': [event: GamepadButtonEvent];
  'gamepad-remap': [event: DeviceEvent];
  'gamepad-sensor': [event: GamepadSensorEvent];
  'gamepad-steam-handle': [event: DeviceEvent];
  'clipboard-updated': [event: ClipboardEvent];
  drop: [event: DropEvent];
  'drop-begin': [event: DropEvent];
  'drop-move': [event: DropEvent];
  'drop-complete': [event: DropEvent];
};
