import { AudioDeviceEvent } from './AudioDeviceEvent';
import { CameraDeviceEvent } from './CameraDeviceEvent';
import { ClipboardEvent } from './ClipboardEvent';
import { DisplayEvent } from './DisplayEvent';
import { DropEvent } from './DropEvent';
import { Event } from './Event';
import { GamepadAxisEvent } from './GamepadAxisEvent';
import { GamepadButtonEvent } from './GamepadButtonEvent';
import { GamepadDeviceEvent } from './GamepadDeviceEvent';
import { GamepadSensorEvent } from './GamepadSensorEvent';
import { GamepadTouchpadEvent } from './GamepadTouchpadEvent';
import { JoyAxisEvent } from './JoyAxisEvent';
import { JoyBallEvent } from './JoyBallEvent';
import { JoyBatteryEvent } from './JoyBatteryEvent';
import { JoyButtonEvent } from './JoyButtonEvent';
import { JoyDeviceEvent } from './JoyDeviceEvent';
import { JoyHatEvent } from './JoyHatEvent';
import { KeyboardDeviceEvent } from './KeyboardDeviceEvent';
import { KeyboardEvent } from './KeyboardEvent';
import { MouseButtonEvent } from './MouseButtonEvent';
import { MouseDeviceEvent } from './MouseDeviceEvent';
import { MouseMotionEvent } from './MouseMotionEvent';
import { MouseWheelEvent } from './MouseWheelEvent';
import { PenAxisEvent } from './PenAxisEvent';
import { PenButtonEvent } from './PenButtonEvent';
import { PenMotionEvent } from './PenMotionEvent';
import { PenProximityEvent } from './PenProximityEvent';
import { PenTouchEvent } from './PenTouchEvent';
import { QuitEvent } from './QuitEvent';
import { RenderEvent } from './RenderEvent';
import { SensorEvent } from './SensorEvent';
import { TextEditingCandidatesEvent } from './TextEditingCandidatesEvent';
import { TextEditingEvent } from './TextEditingEvent';
import { TextInputEvent } from './TextInputEvent';
import { TouchFingerEvent } from './TouchFingerEvent';
import { UserEvent } from './UserEvent';
import { WindowEvent } from './WindowEvent';

export { AudioDeviceEvent } from './AudioDeviceEvent';
export { CameraDeviceEvent } from './CameraDeviceEvent';
export { ClipboardEvent } from './ClipboardEvent';
export { DisplayEvent } from './DisplayEvent';
export { DropEvent } from './DropEvent';
export { Event } from './Event';
export { GamepadAxisEvent } from './GamepadAxisEvent';
export { GamepadButtonEvent } from './GamepadButtonEvent';
export { GamepadDeviceEvent } from './GamepadDeviceEvent';
export { GamepadSensorEvent } from './GamepadSensorEvent';
export { GamepadTouchpadEvent } from './GamepadTouchpadEvent';
export { JoyAxisEvent } from './JoyAxisEvent';
export { JoyBallEvent } from './JoyBallEvent';
export { JoyBatteryEvent } from './JoyBatteryEvent';
export { JoyButtonEvent } from './JoyButtonEvent';
export { JoyDeviceEvent } from './JoyDeviceEvent';
export { JoyHatEvent } from './JoyHatEvent';
export { KeyboardDeviceEvent } from './KeyboardDeviceEvent';
export { KeyboardEvent } from './KeyboardEvent';
export { MouseButtonEvent } from './MouseButtonEvent';
export { MouseDeviceEvent } from './MouseDeviceEvent';
export { MouseMotionEvent } from './MouseMotionEvent';
export { MouseWheelEvent } from './MouseWheelEvent';
export { PenAxisEvent } from './PenAxisEvent';
export { PenButtonEvent } from './PenButtonEvent';
export { PenMotionEvent } from './PenMotionEvent';
export { PenProximityEvent } from './PenProximityEvent';
export { PenTouchEvent } from './PenTouchEvent';
export { QuitEvent } from './QuitEvent';
export { RenderEvent } from './RenderEvent';
export { SensorEvent } from './SensorEvent';
export { TextEditingCandidatesEvent } from './TextEditingCandidatesEvent';
export { TextEditingEvent } from './TextEditingEvent';
export { TextInputEvent } from './TextInputEvent';
export { TouchFingerEvent } from './TouchFingerEvent';
export { UserEvent } from './UserEvent';
export { WindowEvent } from './WindowEvent';

export type SDL_EventMap = {
  audioDevice: [AudioDeviceEvent];
  cameraDevice: [CameraDeviceEvent];
  clipboard: [ClipboardEvent];
  display: [DisplayEvent];
  drop: [DropEvent];
  event: [Event];
  gamepadAxis: [GamepadAxisEvent];
  gamepadButton: [GamepadButtonEvent];
  gamepadDevice: [GamepadDeviceEvent];
  gamepadSensor: [GamepadSensorEvent];
  gamepadTouchpad: [GamepadTouchpadEvent];
  joyAxis: [JoyAxisEvent];
  joyBall: [JoyBallEvent];
  joyBattery: [JoyBatteryEvent];
  joyButton: [JoyButtonEvent];
  joyDevice: [JoyDeviceEvent];
  joyHat: [JoyHatEvent];
  keyboardDevice: [KeyboardDeviceEvent];
  keyboard: [KeyboardEvent];
  mouseButton: [MouseButtonEvent];
  mouseDevice: [MouseDeviceEvent];
  mouseMotion: [MouseMotionEvent];
  mouseWheel: [MouseWheelEvent];
  penAxis: [PenAxisEvent];
  penButton: [PenButtonEvent];
  penMotion: [PenMotionEvent];
  penProximity: [PenProximityEvent];
  penTouch: [PenTouchEvent];
  quit: [QuitEvent];
  render: [RenderEvent];
  sensor: [SensorEvent];
  textEditingCandidates: [TextEditingCandidatesEvent];
  textEditing: [TextEditingEvent];
  textInput: [TextInputEvent];
  touchFinger: [TouchFingerEvent];
  user: [UserEvent];
  window: [WindowEvent];
};
