/**
 * @description https://wiki.libsdl.org/SDL3/SDL_MatrixCoefficients
 */
export enum SDL_MatrixCoefficients {
  SDL_MATRIX_COEFFICIENTS_IDENTITY = 0,
  SDL_MATRIX_COEFFICIENTS_BT709 = 1 /**< ITU-R BT.709-6 */,
  SDL_MATRIX_COEFFICIENTS_UNSPECIFIED = 2,
  SDL_MATRIX_COEFFICIENTS_FCC = 4 /**< US FCC Title 47 */,
  SDL_MATRIX_COEFFICIENTS_BT470BG = 5 /**< ITU-R BT.470-6 System B, G / ITU-R BT.601-7 625, functionally the same as SDL_MATRIX_COEFFICIENTS_BT601 */,
  SDL_MATRIX_COEFFICIENTS_BT601 = 6 /**< ITU-R BT.601-7 525 */,
  SDL_MATRIX_COEFFICIENTS_SMPTE240 = 7 /**< SMPTE 240M */,
  SDL_MATRIX_COEFFICIENTS_YCGCO = 8,
  SDL_MATRIX_COEFFICIENTS_BT2020_NCL = 9 /**< ITU-R BT.2020-2 non-constant luminance */,
  SDL_MATRIX_COEFFICIENTS_BT2020_CL = 10 /**< ITU-R BT.2020-2 constant luminance */,
  SDL_MATRIX_COEFFICIENTS_SMPTE2085 = 11 /**< SMPTE ST 2085 */,
  SDL_MATRIX_COEFFICIENTS_CHROMA_DERIVED_NCL = 12,
  SDL_MATRIX_COEFFICIENTS_CHROMA_DERIVED_CL = 13,
  SDL_MATRIX_COEFFICIENTS_ICTCP = 14 /**< ITU-R BT.2100-0 ICTCP */,
  SDL_MATRIX_COEFFICIENTS_CUSTOM = 31,
}
