/**
 * @description https://wiki.libsdl.org/SDL3/SDL_ArrayOrder
 */
export enum SDL_ArrayOrder {
  SDL_ARRAYORDER_NONE,
  SDL_ARRAYORDER_RGB,
  SDL_ARRAYORDER_RGBA,
  SDL_ARRAYORDER_ARGB,
  SDL_ARRAYORDER_BGR,
  SDL_ARRAYORDER_BGRA,
  SDL_ARRAYORDER_ABGR,
}
