name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug] '
labels: ['bug', 'needs-triage']
assignees: []
projects: ['vulppi-dev/2']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short description of the bug.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to Solve
      description: What problem or limitation does this bug represent?
      placeholder: The application crashes when opening a file with special characters in the name.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe how you think the bug should be fixed.
      placeholder: Sanitize file names before processing to handle special characters.
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope of Impact
      description: Which area does this improvement affect?
      multiple: true
      options:
        - UI/UX
        - API / SDK
        - Performance
        - Security
        - Documentation
        - Tooling
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this improvement to you?
      options:
        - Critical (blocks usage)
        - High (strongly improves workflow)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues and Discussions
          required: true
        - label: I have read the contributing guidelines
          required: false
        - label: I agree to follow the Code of Conduct
          required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details (optional)
      description: How can we reach you if we need clarification?
      placeholder: email or @handle
    validations:
      required: false
