name: Bug Report
description: Report a reproducible bug to help us improve
title: "[BUG] <short summary>"
labels: ["bug", "needs-triage"]
assignees: []
projects: ["vulppi-dev/2"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug.
        Please provide as much detail as possible so we can reproduce and fix it quickly.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A one-sentence description of the problem.
      placeholder: e.g., Crash when clicking "Save" on the settings page
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Exact, numbered steps so anyone can reproduce the issue.
      placeholder: |
        1. Go to Settings → Profile
        2. Click "Save" with empty name
        3. Observe the crash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you thought should happen.
      placeholder: The profile should save successfully or show a validation error.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include full error messages).
      placeholder: The app crashes with "TypeError: cannot read properties of undefined".
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How bad is the impact?
      options:
        - Critical (data loss, security, crash on launch)
        - High (major feature broken, blocks workflow)
        - Medium (workaround exists)
        - Low (minor issue, cosmetic)
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does it happen?
      options:
        - Always
        - Often
        - Sometimes
        - Rarely
        - Unable to determine
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App/Package Version
      description: Version or commit where the issue occurs (semver or SHA).
      placeholder: v1.4.2 or 3f2a9c1
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Tell us where this occurred.
      placeholder: |
        OS: Windows 11
        Bun: 1.2.x
        validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs & Stack Traces
      description: Paste relevant logs. Use code fences for readability.
      placeholder: |
        ```
        <paste logs here>
        ```
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recording
      description: Drag-and-drop images or link to a video/GIF that shows the issue.
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues and Discussions
          required: true
        - label: I have read the contributing guidelines
          required: false
        - label: I agree to follow the Code of Conduct
          required: true
