name: Support / Question
description: Ask a question or request support
title: '[Support] <short summary>'
labels: ['question', 'needs-triage']
assignees: []
projects: ['vulppi-dev/2']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Use this form if you need help, clarification, or have general questions.  
        If this is a **bug** or a **feature request**, please use the corresponding template.

  - type: input
    id: summary
    attributes:
      label: Question Summary
      description: A short title for your question.
      placeholder: How can I configure Bunbox with custom plugins?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Describe what you are trying to achieve, and why you need help.
      placeholder: I'm trying to integrate Bunbox with SDL3, but I'm not sure how to set up the window flags...
    validations:
      required: true

  - type: textarea
    id: attempts
    attributes:
      label: What Have You Tried?
      description: Explain what you already tried or researched before asking.
      placeholder: I looked at the docs and tried changing the flags, but the window still opens in the wrong mode.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Share details about your setup to help others reproduce or understand the context.
      placeholder: |
        OS: Windows 11  
        Bun: 1.2.x  
        Node: 22.x  
        Project version: v0.3.0
    validations:
      required: false

  - type: checkboxes
    id: confirmations
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues and Discussions
          required: true
        - label: I have read the documentation
          required: false
        - label: I agree to follow the Code of Conduct
          required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details (optional)
      description: How can we reach you if we need clarification?
      placeholder: email or @handle
    validations:
      required: false
