// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineWindowState } from "./EngineWindowState";

export type EngineCmd = { "type": "createWindow", "content": { title: string, width: number, height: number, x: number, y: number, borderless: boolean, resizable: boolean, opacity: number, state: EngineWindowState, alwaysOnTop: boolean, } };
