/**
 * @description https://wiki.libsdl.org/SDL3/SDL_GPUSwapchainComposition
 */
export enum SDL_GPUSwapchainComposition {
  SDL_GPU_SWAPCHAINCOMPOSITION_SDR,
  SDL_GPU_SWAPCHAINCOMPOSITION_SDR_LINEAR,
  SDL_GPU_SWAPCHAINCOMPOSITION_HDR_EXTENDED_LINEAR,
  SDL_GPU_SWAPCHAINCOMPOSITION_HDR10_ST2084,
}
