/**
 * @description https://wiki.libsdl.org/SDL3/SDL_GPUVertexElementFormat
 */
export enum SDL_GPUVertexElementFormat {
  SDL_GPU_VERTEXELEMENTFORMAT_INVALID,

  /* 32-bit Signed Integers */
  SDL_GPU_VERTEXELEMENTFORMAT_INT,
  SDL_GPU_VERTEXELEMENTFORMAT_INT2,
  SDL_GPU_VERTEXELEMENTFORMAT_INT3,
  SDL_GPU_VERTEXELEMENTFORMAT_INT4,

  /* 32-bit Unsigned Integers */
  SDL_GPU_VERTEXELEMENTFORMAT_UINT,
  SDL_GPU_VERTEXELEMENTFORMAT_UINT2,
  SDL_GPU_VERTEXELEMENTFORMAT_UINT3,
  SDL_GPU_VERTEXELEMENTFORMAT_UINT4,

  /* 32-bit Floats */
  SDL_GPU_VERTEXELEMENTFORMAT_FLOAT,
  SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2,
  SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3,
  SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4,

  /* 8-bit Signed Integers */
  SDL_GPU_VERTEXELEMENTFORMAT_BYTE2,
  SDL_GPU_VERTEXELEMENTFORMAT_BYTE4,

  /* 8-bit Unsigned Integers */
  SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2,
  SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4,

  /* 8-bit Signed Normalized */
  SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM,
  SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM,

  /* 8-bit Unsigned Normalized */
  SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM,
  SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM,

  /* 16-bit Signed Integers */
  SDL_GPU_VERTEXELEMENTFORMAT_SHORT2,
  SDL_GPU_VERTEXELEMENTFORMAT_SHORT4,

  /* 16-bit Unsigned Integers */
  SDL_GPU_VERTEXELEMENTFORMAT_USHORT2,
  SDL_GPU_VERTEXELEMENTFORMAT_USHORT4,

  /* 16-bit Signed Normalized */
  SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM,
  SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM,

  /* 16-bit Unsigned Normalized */
  SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM,
  SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM,

  /* 16-bit Floats */
  SDL_GPU_VERTEXELEMENTFORMAT_HALF2,
  SDL_GPU_VERTEXELEMENTFORMAT_HALF4,
}
