/**
 * @description https://wiki.libsdl.org/SDL3/SDL_GPUCubeMapFace
 */
export enum SDL_GPUCubeMapFace {
  SDL_GPU_CUBEMAPFACE_POSITIVEX,
  SDL_GPU_CUBEMAPFACE_NEGATIVEX,
  SDL_GPU_CUBEMAPFACE_POSITIVEY,
  SDL_GPU_CUBEMAPFACE_NEGATIVEY,
  SDL_GPU_CUBEMAPFACE_POSITIVEZ,
  SDL_GPU_CUBEMAPFACE_NEGATIVEZ,
}
