/**
 * @description https://wiki.libsdl.org/SDL3/SDL_JoystickHat
 */
export enum SDL_JoystickHat {
  SDL_HAT_CENTERED = 0x00,
  SDL_HAT_UP = 0x01,
  SDL_HAT_RIGHT = 0x02,
  SDL_HAT_DOWN = 0x04,
  SDL_HAT_LEFT = 0x08,
  SDL_HAT_RIGHTUP = SDL_HAT_RIGHT | SDL_HAT_UP,
  SDL_HAT_RIGHTDOWN = SDL_HAT_RIGHT | SDL_HAT_DOWN,
  SDL_HAT_LEFTUP = SDL_HAT_LEFT | SDL_HAT_UP,
  SDL_HAT_LEFTDOWN = SDL_HAT_LEFT | SDL_HAT_DOWN,
}
