/**
 * @description https://wiki.libsdl.org/SDL3/SDL_PropertyType
 */
export enum SDL_PropertyType {
  SDL_PROPERTY_TYPE_INVALID,
  SDL_PROPERTY_TYPE_POINTER,
  SDL_PROPERTY_TYPE_STRING,
  SDL_PROPERTY_TYPE_NUMBER,
  SDL_PROPERTY_TYPE_FLOAT,
  SDL_PROPERTY_TYPE_BOOLEAN,
}
