/**
 * @description https://wiki.libsdl.org/SDL3/SDL_InitStatus
 */
export enum SDL_InitStatus {
  SDL_INIT_STATUS_UNINITIALIZED,
  SDL_INIT_STATUS_INITIALIZING,
  SDL_INIT_STATUS_INITIALIZED,
  SDL_INIT_STATUS_UNINITIALIZING,
}
