/**
 * @description https://wiki.libsdl.org/SDL3/SDL_GamepadAxis
 */
export enum SDL_GamepadAxis {
  SDL_GAMEPAD_AXIS_INVALID = -1,
  SDL_GAMEPAD_AXIS_LEFTX,
  SDL_GAMEPAD_AXIS_LEFTY,
  SDL_GAMEPAD_AXIS_RIGHTX,
  SDL_GAMEPAD_AXIS_RIGHTY,
  SDL_GAMEPAD_AXIS_LEFT_TRIGGER,
  SDL_GAMEPAD_AXIS_RIGHT_TRIGGER,
  SDL_GAMEPAD_AXIS_COUNT,
}
