/**
 * @description https://wiki.libsdl.org/SDL3/SDL_GamepadType
 */
export enum SDL_GamepadType {
  SDL_GAMEPAD_TYPE_UNKNOWN = 0,
  SDL_GAMEPAD_TYPE_STANDARD,
  SDL_GAMEPAD_TYPE_XBOX360,
  SDL_GAMEPAD_TYPE_XBOXONE,
  SDL_GAMEPAD_TYPE_PS3,
  SDL_GAMEPAD_TYPE_PS4,
  SDL_GAMEPAD_TYPE_PS5,
  SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO,
  SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT,
  SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT,
  SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR,
  SDL_GAMEPAD_TYPE_GAMECUBE,
  SDL_GAMEPAD_TYPE_COUNT,
}
