/**
 * @description https://wiki.libsdl.org/SDL3/SDL_GamepadButtonLabel
 */
export enum SDL_GamepadButtonLabel {
  SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN,
  SDL_GAMEPAD_BUTTON_LABEL_A,
  SDL_GAMEPAD_BUTTON_LABEL_B,
  SDL_GAMEPAD_BUTTON_LABEL_X,
  SDL_GAMEPAD_BUTTON_LABEL_Y,
  SDL_GAMEPAD_BUTTON_LABEL_CROSS,
  SDL_GAMEPAD_BUTTON_LABEL_CIRCLE,
  SDL_GAMEPAD_BUTTON_LABEL_SQUARE,
  SDL_GAMEPAD_BUTTON_LABEL_TRIANGLE,
}
