name: Build FreeType

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-freetype.yml'

jobs:
  linux-x64:
    name: Linux x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      # Build FreeType
      - name: Clone and build FreeType
        run: |
          git clone --depth 1 https://github.com/freetype/freetype.git freetype
          cd freetype
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DFT_DISABLE_HARFBUZZ=ON -DFT_DISABLE_BZIP2=ON -DFT_DISABLE_PNG=ON -DFT_DISABLE_BROTLI=ON
          cmake --build build --config Release
          strip build/libfreetype.so*

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/x64/linux
          cp freetype/build/libfreetype.so* artifacts/x64/linux/libfreetype.so || cp freetype/build/libfreetype.so artifacts/x64/linux/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: artifacts/
          retention-days: 7

  linux-arm64:
    name: Linux ARM64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -yq update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Prepare cross-compilation for arm64
        run: |
          sudo grep 'deb ' /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
          sudo sed -i 's/^deb /deb [arch=amd64] /' /etc/apt/sources.list
          sudo sed -i 's#^deb [^ ]\+#deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports/#' /etc/apt/sources.list.d/ports.list
          sudo dpkg --add-architecture arm64
          sudo apt-get update || true

      - name: Install cross-compilation dependencies
        run: sudo apt-get -yq --allow-unauthenticated install libgl1-mesa-dev:arm64 x11proto-dev libx11-dev:arm64 libxml2:arm64 -o Dpkg::Options::="--force-overwrite"

      # Build FreeType
      - name: Clone and build FreeType
        run: |
          git clone --depth 1 https://github.com/freetype/freetype.git freetype
          cd freetype
          cat > toolchain-aarch64.cmake << 'EOF'
          set(CMAKE_SYSTEM_NAME Linux)
          set(CMAKE_SYSTEM_PROCESSOR aarch64)
          set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
          set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
          set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
          set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
          set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
          set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
          EOF
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=toolchain-aarch64.cmake \
            -DBUILD_SHARED_LIBS=ON \
            -DFT_DISABLE_HARFBUZZ=ON \
            -DFT_DISABLE_BZIP2=ON \
            -DFT_DISABLE_PNG=ON \
            -DFT_DISABLE_BROTLI=ON
          cmake --build build --config Release
          aarch64-linux-gnu-strip build/libfreetype.so* || true

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/arm64/linux logs/linux-arm64

          echo "--- FreeType build output ---" > logs/linux-arm64/freetype.txt
          ls -la freetype/build 2>/dev/null || true >> logs/linux-arm64/freetype.txt
          if compgen -G "freetype/build/libfreetype*.so*" > /dev/null; then
            cp freetype/build/libfreetype*.so* artifacts/arm64/linux/ || true
            echo "FreeType: copied" >> logs/linux-arm64/freetype.txt
          else
            echo "FreeType: not built" >> logs/linux-arm64/freetype.txt
            touch artifacts/arm64/linux/libfreetype.so
          fi

          ls -la artifacts/arm64/linux || true
          cp -r logs/linux-arm64 artifacts/arm64/linux/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: artifacts/
          retention-days: 7

  macos:
    name: macOS
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x64, arm64]
        include:
          - ARCH: x64
            PLATFORM: osx-x64
            CMAKE_ARCH: x86_64
            OSX_MIN: '10.15.4'
          - ARCH: arm64
            PLATFORM: osx-arm64
            CMAKE_ARCH: arm64
            OSX_MIN: '11.0'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      # Build FreeType
      - name: Clone and build FreeType
        run: |
          git clone --depth 1 https://github.com/freetype/freetype.git freetype
          cd freetype
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES=${{matrix.CMAKE_ARCH}} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=${{matrix.OSX_MIN}} \
            -DBUILD_SHARED_LIBS=ON \
            -DFT_DISABLE_HARFBUZZ=ON \
            -DFT_DISABLE_BZIP2=ON \
            -DFT_DISABLE_PNG=ON \
            -DFT_DISABLE_BROTLI=ON
          cmake --build build --config Release
          strip -u -r build/libfreetype*.dylib

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/${{matrix.ARCH}}/darwin
          find freetype/build -name "libfreetype*.dylib" -exec cp {} artifacts/${{matrix.ARCH}}/darwin/libfreetype.dylib \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{matrix.ARCH}}
          path: artifacts/
          retention-days: 7

  windows-x64:
    name: Windows x64
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      # Build FreeType
      - name: Clone and build FreeType
        run: |
          git clone --depth 1 https://github.com/freetype/freetype.git freetype
          cd freetype
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DFT_DISABLE_HARFBUZZ=ON -DFT_DISABLE_BZIP2=ON -DFT_DISABLE_PNG=ON -DFT_DISABLE_BROTLI=ON
          cmake --build build --config Release

      - name: Prepare artifacts
        run: |
          mkdir artifacts\x64\win32
          copy freetype\build\Release\freetype.dll artifacts\x64\win32\freetype.dll
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: artifacts/
          retention-days: 7
