name: Build GLFW

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-glfw.yml'

jobs:
  linux-x64:
    name: Linux x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      # Build GLFW
      - name: Install GLFW dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev

      - name: Clone and build GLFW
        run: |
          git clone --depth 1 https://github.com/glfw/glfw.git glfw
          cd glfw
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
          cmake --build build --config Release
          strip build/src/libglfw.so*

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/x64/linux
          cp glfw/build/src/libglfw.so* artifacts/x64/linux/libglfw.so || cp glfw/build/src/libglfw.so artifacts/x64/linux/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: artifacts/
          retention-days: 7

  linux-arm64:
    name: Linux ARM64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -yq update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Prepare cross-compilation for arm64
        run: |
          sudo grep 'deb ' /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
          sudo sed -i 's/^deb /deb [arch=amd64] /' /etc/apt/sources.list
          sudo sed -i 's#^deb [^ ]\+#deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports/#' /etc/apt/sources.list.d/ports.list
          sudo dpkg --add-architecture arm64
          sudo apt-get update || true

      - name: Install cross-compilation dependencies
        run: sudo apt-get -yq --allow-unauthenticated install libgl1-mesa-dev:arm64 x11proto-dev libx11-dev:arm64 libxml2:arm64 -o Dpkg::Options::="--force-overwrite"

      # Build GLFW
      - name: Clone and build GLFW
        run: |
          git clone --depth 1 https://github.com/glfw/glfw.git glfw
          cd glfw
          cat > toolchain-aarch64.cmake << 'EOF'
          set(CMAKE_SYSTEM_NAME Linux)
          set(CMAKE_SYSTEM_PROCESSOR aarch64)
          set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
          set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
          set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
          set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
          set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
          set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
          EOF
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=toolchain-aarch64.cmake \
            -DBUILD_SHARED_LIBS=ON \
            -DGLFW_BUILD_EXAMPLES=OFF \
            -DGLFW_BUILD_TESTS=OFF \
            -DGLFW_BUILD_DOCS=OFF \
            -DGLFW_BUILD_WAYLAND=OFF \
            -DGLFW_BUILD_X11=OFF || echo "GLFW build may fail on ARM64 cross-compilation"
          cmake --build build --config Release || echo "GLFW build failed, continuing..."

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/arm64/linux

          # Copy GLFW if present, otherwise create a placeholder
          if compgen -G "glfw/build/src/libglfw*.so*" > /dev/null; then
            cp glfw/build/src/libglfw*.so* artifacts/arm64/linux/libglfw.so || true
          else
            touch artifacts/arm64/linux/libglfw.so
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: artifacts/
          retention-days: 7

  macos:
    name: macOS
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x64, arm64]
        include:
          - ARCH: x64
            PLATFORM: osx-x64
            CMAKE_ARCH: x86_64
            OSX_MIN: '10.15.4'
          - ARCH: arm64
            PLATFORM: osx-arm64
            CMAKE_ARCH: arm64
            OSX_MIN: '11.0'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      # Build GLFW
      - name: Clone and build GLFW
        run: |
          git clone --depth 1 https://github.com/glfw/glfw.git glfw
          cd glfw
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES=${{matrix.CMAKE_ARCH}} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=${{matrix.OSX_MIN}} \
            -DBUILD_SHARED_LIBS=ON \
            -DGLFW_BUILD_EXAMPLES=OFF \
            -DGLFW_BUILD_TESTS=OFF \
            -DGLFW_BUILD_DOCS=OFF
          cmake --build build --config Release
          strip -u -r build/src/libglfw*.dylib

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/${{matrix.ARCH}}/darwin
          find glfw/build/src -name "libglfw*.dylib" -exec cp {} artifacts/${{matrix.ARCH}}/darwin/libglfw.dylib \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{matrix.ARCH}}
          path: artifacts/
          retention-days: 7

  windows-x64:
    name: Windows x64
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      # Build GLFW
      - name: Clone and build GLFW
        run: |
          git clone --depth 1 https://github.com/glfw/glfw.git glfw
          cd glfw
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF
          cmake --build build --config Release

      - name: Prepare artifacts
        run: |
          mkdir artifacts\x64\win32\
          copy glfw\build\src\Release\glfw3.dll artifacts\x64\win32\glfw3.dll
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: artifacts/
          retention-days: 7
