name: Build BGFX shaderc

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-bgfx-shaderc.yml'

jobs:
  linux-x64:
    name: Linux x64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Install dependencies
        run: sudo apt-get install -y libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev x11proto-dev libx11-dev

      - name: Clone bx, bimg & GENie
        run: |
          git clone --depth 1 https://github.com/bkaradzic/bx.git bx
          git clone --depth 1 https://github.com/bkaradzic/bimg.git bimg
          git clone https://github.com/bkaradzic/GENie.git GENie
          cd GENie
          make

      - name: Build bgfx shaderc
        run: |
          git clone --depth 1 https://github.com/bkaradzic/bgfx.git bgfx
          cd bgfx
          ../GENie/bin/linux/genie --gcc=linux-gcc gmake
          make -R -C .build/projects/gmake-linux-gcc config=release64 shaderc
          strip .build/linux64_gcc/bin/shadercRelease

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/x64/linux
          cp bgfx/.build/linux64_gcc/bin/shadercRelease artifacts/x64/linux/shaderc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: artifacts/
          retention-days: 7

  linux-arm64:
    name: Linux ARM64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Install dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get -yq update
          DEBIAN_FRONTEND=noninteractive sudo apt-get -yq install cmake gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Prepare cross-compilation for arm64
        run: |
          sudo grep 'deb ' /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/ports.list
          sudo sed -i 's/^deb /deb [arch=amd64] /' /etc/apt/sources.list
          sudo sed -i 's#^deb [^ ]\+#deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports/#' /etc/apt/sources.list.d/ports.list
          sudo dpkg --add-architecture arm64
          sudo apt-get update || true

      - name: Install cross-compilation dependencies
        run: sudo apt-get -yq --allow-unauthenticated install libgl1-mesa-dev:arm64 x11proto-dev libx11-dev:arm64 libxml2:arm64 -o Dpkg::Options::="--force-overwrite"

      - name: Clone bx, bimg & GENie
        run: |
          git clone --depth 1 https://github.com/bkaradzic/bx.git bx
          git clone --depth 1 https://github.com/bkaradzic/bimg.git bimg
          git clone https://github.com/bkaradzic/GENie.git GENie
          cd GENie
          make

      - name: Build bgfx shaderc
        run: |
          git clone --depth 1 https://github.com/bkaradzic/bgfx.git bgfx
          cd bgfx

          # Modify toolchain.lua to use correct strip command
          sed -i 's/strip -s/aarch64-linux-gnu-strip/' ../bx/scripts/toolchain.lua

          ../GENie/bin/linux/genie --gcc=linux-arm-gcc gmake

          make -R -C .build/projects/gmake-linux-arm-gcc config=release \
            CXX="aarch64-linux-gnu-g++" \
            CC="aarch64-linux-gnu-gcc" \
            CFLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" \
            shaderc

          aarch64-linux-gnu-strip .build/linux32_arm_gcc/bin/shadercRelease

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/arm64/linux

          SHADERC_EXPECTED="bgfx/.build/linux32_arm_gcc/bin/shadercRelease"
          if [ -f "$SHADERC_EXPECTED" ]; then
            cp "$SHADERC_EXPECTED" artifacts/arm64/linux/shaderc
          else
            find bgfx/.build -name "shaderc*" -type f -executable -print -exec cp {} artifacts/arm64/linux/shaderc \; -quit 2>/dev/null || true
            if [ ! -f artifacts/arm64/linux/shaderc ]; then
              exit 1
            fi
          fi

          if [ ! -s artifacts/arm64/linux/shaderc ]; then
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64
          path: artifacts/
          retention-days: 7

  macos:
    name: macOS
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x64, arm64]
        include:
          - ARCH: x64
            PLATFORM: osx-x64
            CMAKE_ARCH: x86_64
            OSX_MIN: '10.15.4'
          - ARCH: arm64
            PLATFORM: osx-arm64
            CMAKE_ARCH: arm64
            OSX_MIN: '11.0'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Clone bx, bimg & GENie
        run: |
          git clone --depth 1 https://github.com/bkaradzic/bx.git bx
          git clone --depth 1 https://github.com/bkaradzic/bimg.git bimg

      - name: Build bgfx shaderc
        run: |
          git clone --depth 1 https://github.com/bkaradzic/bgfx.git bgfx
          cd bgfx
          MACOSX_DEPLOYMENT_TARGET=${{matrix.OSX_MIN}} \
          CFLAGS="-mmacosx-version-min=${{matrix.OSX_MIN}}" \
          LDFLAGS="-mmacosx-version-min=${{matrix.OSX_MIN}}" \
          ../bx/tools/bin/darwin/genie --with-macos=${{matrix.OSX_MIN}} --gcc=${{matrix.PLATFORM}} gmake

          MACOSX_DEPLOYMENT_TARGET=${{matrix.OSX_MIN}} \
          CFLAGS="-mmacosx-version-min=${{matrix.OSX_MIN}}" \
          LDFLAGS="-mmacosx-version-min=${{matrix.OSX_MIN}}" \
          make -C .build/projects/gmake-${{matrix.PLATFORM}} config=release64 shaderc
          strip -u -r .build/${{matrix.PLATFORM}}/bin/shadercRelease

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/${{matrix.ARCH}}/darwin
          cp bgfx/.build/${{matrix.PLATFORM}}/bin/shadercRelease artifacts/${{matrix.ARCH}}/darwin/shaderc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{matrix.ARCH}}
          path: artifacts/
          retention-days: 7

  windows-x64:
    name: Windows x64
    runs-on: windows-2022
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Clone bx, bimg & GENie
        run: |
          git clone --depth 1 https://github.com/bkaradzic/bx.git bx
          git clone --depth 1 https://github.com/bkaradzic/bimg.git bimg
          git clone https://github.com/bkaradzic/GENie.git GENie
          cd GENie
          nmake -f scripts\genie.mak windows
        shell: cmd

      - name: Build bgfx shaderc
        run: |
          git clone --depth 1 https://github.com/bkaradzic/bgfx.git bgfx
          cd bgfx
          ..\GENie\bin\windows\genie.exe --gcc=mingw-gcc gmake
          cd .build\projects\gmake-mingw-gcc
          mingw32-make config=release64 shaderc
        shell: cmd

      - name: Prepare artifacts
        run: |
          mkdir artifacts\x64\win32
          copy bgfx\.build\win64_mingw-gcc\bin\shadercRelease.exe artifacts\x64\win32\shaderc.exe
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: artifacts/
          retention-days: 7
