// LLGL MARK: RenderSystem

export enum LLGL_RenderSystemFlags {
  /** Prefer hardware device over software device. */
  PREFER_HARDWARE = 1 << 0,

  /** Debug mode flag for renderer. */
  DEBUG_DEVICE = 1 << 1,
}

// LLGL MARK: Format

export enum LLGL_Format {
  UNDEFINED = 0,

  // Color formats
  R8_UNORM = 1,
  R8_SNORM = 2,
  R8_UINT = 3,
  R8_SINT = 4,

  R16_UNORM = 5,
  R16_SNORM = 6,
  R16_UINT = 7,
  R16_SINT = 8,
  R16_FLOAT = 9,

  R32_UINT = 10,
  R32_SINT = 11,
  R32_FLOAT = 12,

  RG8_UNORM = 13,
  RG8_SNORM = 14,
  RG8_UINT = 15,
  RG8_SINT = 16,

  RG16_UNORM = 17,
  RG16_SNORM = 18,
  RG16_UINT = 19,
  RG16_SINT = 20,
  RG16_FLOAT = 21,

  RG32_UINT = 22,
  RG32_SINT = 23,
  RG32_FLOAT = 24,

  RGB8_UNORM = 25,
  RGB8_SNORM = 26,
  RGB8_UINT = 27,
  RGB8_SINT = 28,

  RGB16_UNORM = 29,
  RGB16_SNORM = 30,
  RGB16_UINT = 31,
  RGB16_SINT = 32,
  RGB16_FLOAT = 33,

  RGB32_UINT = 34,
  RGB32_SINT = 35,
  RGB32_FLOAT = 36,

  RGBA8_UNORM = 37,
  RGBA8_SNORM = 38,
  RGBA8_UINT = 39,
  RGBA8_SINT = 40,

  RGBA16_UNORM = 41,
  RGBA16_SNORM = 42,
  RGBA16_UINT = 43,
  RGBA16_SINT = 44,
  RGBA16_FLOAT = 45,

  RGBA32_UINT = 46,
  RGBA32_SINT = 47,
  RGBA32_FLOAT = 48,

  BGRA8_UNORM = 49,
  BGRA8_UNORM_SRGB = 50,
  BGRA8_SNORM = 51,
  BGRA8_UINT = 52,
  BGRA8_SINT = 53,

  // Depth-stencil formats
  D16_UNORM = 54,
  D24_UNORM_S8_UINT = 55,
  D32_FLOAT = 56,
  D32_FLOAT_S8X24_UINT = 57,

  // Compressed formats
  BC1_UNORM = 58,
  BC1_UNORM_SRGB = 59,
  BC2_UNORM = 60,
  BC2_UNORM_SRGB = 61,
  BC3_UNORM = 62,
  BC3_UNORM_SRGB = 63,
}

// LLGL MARK: PrimitiveTopology

export enum LLGL_PrimitiveTopology {
  POINT_LIST = 0,
  LINE_LIST = 1,
  LINE_STRIP = 2,
  LINE_LIST_ADJACENCY = 3,
  LINE_STRIP_ADJACENCY = 4,
  TRIANGLE_LIST = 5,
  TRIANGLE_STRIP = 6,
  TRIANGLE_FAN = 7,
  TRIANGLE_LIST_ADJACENCY = 8,
  TRIANGLE_STRIP_ADJACENCY = 9,

  // Patch list with N control points
  PATCH_LIST_1_CONTROL_POINT = 10,
  PATCH_LIST_2_CONTROL_POINTS = 11,
  PATCH_LIST_3_CONTROL_POINTS = 12,
  PATCH_LIST_4_CONTROL_POINTS = 13,
  PATCH_LIST_5_CONTROL_POINTS = 14,
  PATCH_LIST_6_CONTROL_POINTS = 15,
  PATCH_LIST_7_CONTROL_POINTS = 16,
  PATCH_LIST_8_CONTROL_POINTS = 17,
  PATCH_LIST_9_CONTROL_POINTS = 18,
  PATCH_LIST_10_CONTROL_POINTS = 19,
  PATCH_LIST_11_CONTROL_POINTS = 20,
  PATCH_LIST_12_CONTROL_POINTS = 21,
  PATCH_LIST_13_CONTROL_POINTS = 22,
  PATCH_LIST_14_CONTROL_POINTS = 23,
  PATCH_LIST_15_CONTROL_POINTS = 24,
  PATCH_LIST_16_CONTROL_POINTS = 25,
  PATCH_LIST_17_CONTROL_POINTS = 26,
  PATCH_LIST_18_CONTROL_POINTS = 27,
  PATCH_LIST_19_CONTROL_POINTS = 28,
  PATCH_LIST_20_CONTROL_POINTS = 29,
  PATCH_LIST_21_CONTROL_POINTS = 30,
  PATCH_LIST_22_CONTROL_POINTS = 31,
  PATCH_LIST_23_CONTROL_POINTS = 32,
  PATCH_LIST_24_CONTROL_POINTS = 33,
  PATCH_LIST_25_CONTROL_POINTS = 34,
  PATCH_LIST_26_CONTROL_POINTS = 35,
  PATCH_LIST_27_CONTROL_POINTS = 36,
  PATCH_LIST_28_CONTROL_POINTS = 37,
  PATCH_LIST_29_CONTROL_POINTS = 38,
  PATCH_LIST_30_CONTROL_POINTS = 39,
  PATCH_LIST_31_CONTROL_POINTS = 40,
  PATCH_LIST_32_CONTROL_POINTS = 41,
}

// LLGL MARK: ResourceType

export enum LLGL_ResourceType {
  UNDEFINED = 0,
  BUFFER = 1,
  TEXTURE = 2,
  SAMPLER = 3,
}

// LLGL MARK: BufferFlags

export enum LLGL_BufferFlags {
  NONE = 0,
  MAP_READ = 1 << 0,
  MAP_WRITE = 1 << 1,
  MAP_PERSISTENT = 1 << 2,
  VERTEX_BUFFER = 1 << 3,
  INDEX_BUFFER = 1 << 4,
  CONSTANT_BUFFER = 1 << 5,
  STORAGE_BUFFER = 1 << 6,
  STREAM_OUTPUT_BUFFER = 1 << 7,
  INDIRECT_BUFFER = 1 << 8,
}

// LLGL MARK: CPUAccessFlags

export enum LLGL_CPUAccessFlags {
  NONE = 0,
  READ = 1 << 0,
  WRITE = 1 << 1,
  READ_WRITE = READ | WRITE,
}

// LLGL MARK: TextureType

export enum LLGL_TextureType {
  TEXTURE_1D = 0,
  TEXTURE_2D = 1,
  TEXTURE_3D = 2,
  TEXTURE_CUBE = 3,
  TEXTURE_1D_ARRAY = 4,
  TEXTURE_2D_ARRAY = 5,
  TEXTURE_CUBE_ARRAY = 6,
  TEXTURE_2D_MS = 7,
  TEXTURE_2D_MS_ARRAY = 8,
}

// LLGL MARK: ShaderType

export enum LLGL_ShaderType {
  VERTEX = 0,
  TESSELLATION_CONTROL = 1,
  TESSELLATION_EVALUATION = 2,
  GEOMETRY = 3,
  FRAGMENT = 4,
  COMPUTE = 5,
}

// LLGL MARK: CompareOp

export enum LLGL_CompareOp {
  NEVER = 0,
  LESS = 1,
  EQUAL = 2,
  LESS_EQUAL = 3,
  GREATER = 4,
  NOT_EQUAL = 5,
  GREATER_EQUAL = 6,
  ALWAYS = 7,
}

// LLGL MARK: StencilOp

export enum LLGL_StencilOp {
  KEEP = 0,
  ZERO = 1,
  REPLACE = 2,
  INCREMENT_CLAMP = 3,
  DECREMENT_CLAMP = 4,
  INVERT = 5,
  INCREMENT_WRAP = 6,
  DECREMENT_WRAP = 7,
}

// LLGL MARK: BlendOp

export enum LLGL_BlendOp {
  ADD = 0,
  SUBTRACT = 1,
  REVERSE_SUBTRACT = 2,
  MIN = 3,
  MAX = 4,
}

// LLGL MARK: BlendArithmetic

export enum LLGL_BlendArithmetic {
  ZERO = 0,
  ONE = 1,
  SRC_COLOR = 2,
  INV_SRC_COLOR = 3,
  SRC_ALPHA = 4,
  INV_SRC_ALPHA = 5,
  DST_COLOR = 6,
  INV_DST_COLOR = 7,
  DST_ALPHA = 8,
  INV_DST_ALPHA = 9,
  SRC_ALPHA_SATURATE = 10,
  BLEND_FACTOR = 11,
  INV_BLEND_FACTOR = 12,
  SRC1_COLOR = 13,
  INV_SRC1_COLOR = 14,
  SRC1_ALPHA = 15,
  INV_SRC1_ALPHA = 16,
}

// LLGL MARK: PolygonMode

export enum LLGL_PolygonMode {
  FILL = 0,
  WIREFRAME = 1,
  POINTS = 2,
}

// LLGL MARK: CullMode

export enum LLGL_CullMode {
  DISABLED = 0,
  FRONT = 1,
  BACK = 2,
}

// LLGL MARK: SamplerAddressMode

export enum LLGL_SamplerAddressMode {
  REPEAT = 0,
  MIRROR = 1,
  CLAMP = 2,
  BORDER = 3,
  MIRROR_ONCE = 4,
}

// LLGL MARK: SamplerFilter

export enum LLGL_SamplerFilter {
  NEAREST = 0,
  LINEAR = 1,
}

// LLGL MARK: CommandBufferFlags

export enum LLGL_CommandBufferFlags {
  NONE = 0,
  IMMEDIATE_SUBMIT = 1 << 0,
  MULTI_SUBMIT = 1 << 1,
}

// LLGL MARK: ClearFlags

export enum LLGL_ClearFlags {
  NONE = 0,
  COLOR = 1 << 0,
  DEPTH = 1 << 1,
  STENCIL = 1 << 2,
  COLOR_DEPTH = COLOR | DEPTH,
  COLOR_DEPTH_STENCIL = COLOR | DEPTH | STENCIL,
  DEPTH_STENCIL = DEPTH | STENCIL,
}

// LLGL MARK: AttachmentLoadOp

export enum LLGL_AttachmentLoadOp {
  UNDEFINED = 0,
  LOAD = 1,
  CLEAR = 2,
}

// LLGL MARK: AttachmentStoreOp

export enum LLGL_AttachmentStoreOp {
  UNDEFINED = 0,
  STORE = 1,
}

// LLGL MARK: IndexFormat

export enum LLGL_IndexFormat {
  UNDEFINED = 0,
  UINT16 = 1,
  UINT32 = 2,
}
